DROP TABLE IF EXISTS files;

CREATE TABLE IF NOT EXISTS files(
    id BIGINT generated by default as identity primary key,
    name VARCHAR(255) NOT NULL,
    type VARCHAR(255) NOT NULL,
    data BIGINT NOT NULL
    );